pipeline:
  test:
    image: python:${PYTHON_VERSION}-alpine3.8
    commands:
      - find . -name "*.py[co]" -delete
      - pip install --upgrade pip
      - pip install -e .
      - pip install -e .[tests]
      - py.test
      - find . -name "*.py[co]" -delete
  build:
    image: python:${PYTHON_VERSION}-alpine3.8
    commands:
      - python setup.py sdist bdist_wheel
      - rm -rf dist
      - rm -rf build
matrix:
  PYTHON_VERSION:
    - "3.7"
    - "3.6"
    - "3.5"
    - "2.7"
