---
kind: pipeline
name: default

steps:
- name: build27
  image: python:2.7-alpine3.8
  commands:
    - ./drone.sh

- name: build35
  image: python:3.5-alpine3.8
  commands:
    - ./drone.sh

- name: build36
  image: python:3.6-alpine3.8
  commands:
    - ./drone.sh

- name: build37
  image: python:3.7-alpine3.8
  commands:
    - ./drone.sh
